removing helper scripts

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,22 +2,17 @@
 
 set -euo pipefail
 
-current_script_path=${BASH_SOURCE[0]}
-plugin_dir=$(dirname "$(dirname "$current_script_path")")
-
-# shellcheck source=../lib/utils.bash
-source "${plugin_dir}/lib/utils.bash"
-
-# ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
-# [ -n "$ASDF_INSTALL_VERSION" ] || (echo >&2 'Missing ASDF_INSTALL_VERSION' && exit 1)
-# [ -n "$ASDF_INSTALL_PATH" ] || (echo >&2 'Missing ASDF_INSTALL_PATH' && exit 1)
+ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
+[ -n "$ASDF_INSTALL_VERSION" ] || (echo >&2 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (echo >&2 'Missing ASDF_INSTALL_PATH' && exit 1)
 
 get_os() {
 	uname | tr '[:upper:]' '[:lower:]'
 }
 
 get_arch() {
-	local arch = $(uname -m)
+	local arch
+	arch="$(uname -m)"
 	case "$arch" in
 	'x86_64') local cpu_type="amd64" ;;
 	'windows') local cpu_type="windows" ;;
@@ -30,9 +25,9 @@ get_arch() {
 }
 
 form_url() {
-	local version = $1
-	local os = get_os
-	local arch = get_arch
+	local version="$1"
+	local os=get_os
+	local arch=get_arch
 	if $arch -eq 'n/a'; then
 		echo "Architecture not supported by Tea" && exit 1
 	fi
@@ -40,7 +35,6 @@ form_url() {
 }
 
 install_version() {
-	local install_type=$1
 	local version=$2
 	local install_path=$3
 	local bin_install_path="$install_path/bin"
